### ISSUE TITLE
Fails to typecheck with latest sail

### ISSUE THREAD

**Issue by arichardson** [CTSRD-CHERI/sail-morello#2]
```
v8_base.sail:38109.24-33:
38109 |    result : bits('N) = undefined;
      |                        ^-------^
      | Type bits('N) is empty
make: *** [Makefile:87: check_sail] Error 1
```

**Comment by Alasdair** [comment]
It might need a `'N >= 0` constraint. There was previously a soundness bug where you could use undefined to create a bitvector of negative length (which should be uninhabited).

**Comment by arichardson** [comment]
CC: @bauereiss

**Comment by bacam** [comment]
I think that the last time an issue like this came up (for tuple assignments), I patched the generated code rather than regenerating it to avoid lots of irrelevant noise.  I think we should probably do the same again now.
